# Generated by Django 5.1 on 2024-09-12 17:43

import django.core.validators
import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(default=store.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCodes',
            fields=[
                ('discount_id', models.CharField(default=store.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('discount_type', models.CharField(max_length=255)),
                ('discount_dollar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_pct', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
            ],
            options={
                'permissions': [('cancel_order', 'Can cancel order')],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_id', models.CharField(default=store.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country_tax_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('state_tax_pct', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(default=store.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField()),
                ('colour', models.CharField(max_length=255)),
                ('shape', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo_id', models.PositiveIntegerField(blank=True, default=None)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('cart_id', models.CharField(default=store.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.user'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('address_id', models.CharField(default=store.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zip_postal_code', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('is_billing', models.BooleanField()),
                ('is_shipping', models.BooleanField()),
                ('tax', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='store.tax')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('payment_id', models.CharField(default=store.models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.discountcodes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.shoppingcart')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
