# Generated by Django 5.1.1 on 2024-10-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_quantity_product_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
