version: "3"

services:
  django:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - INTERNAL_IP=${INTERNAL_IP}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
